version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: "TimeEngineDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Password123"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: TimeEngine.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Host=db;Database=TimeEngineDb;Username=postgres;Password=YourPassword123
    depends_on:
      - db
    ports:
      - "5000:80"

  frontend:
    build:
      context: .
      dockerfile: TimeEngine.SPA/Dockerfile
    depends_on:
      - api
    ports:
      - "4200:80"

volumes:
  pgdata:
