name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build API
        run: dotnet build ./TimeEngine.API --configuration Release

      - name: Run Tests
        run: dotnet test ./tests --configuration Release

      - name: Build Frontend
        working-directory: ./TimeEngine.SPA
        run: |
          npm install
          npm run build -- --prod

      - name: Docker Build
        run: docker-compose -f docker-compose.yml build
